---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes


- name: stat repos
  stat: path=/etc/yum.repos.d/*.repo
  register: repo_stat

- name: rm repos
  command: rm /etc/yum.repos.d/*.repo
  when: repo_stat.stat.exists

#- name: stat epel
#  stat: path=/etc/yum.repos.d/epel*
#  register: epel_stat

#- name: rm epel    
#  command: rm /etc/yum.repos.d/epel*
#  when: epel_stat.stat.exists

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: Run yum clean
#  shell: yum clean all
  command: yum clean all


#- name: setup hostname
#  hostname:
#    name: "{{ inventory_hostname }}"
 
- name: install base tools and packages
  yum:
    name:
      - python-pip
      - gcc
    state: latest
